In [1]:
import pandas as pd


df = pd.read_csv('a9a.txt', header=None, delim_whitespace=True)

print(f"Number of columns: {df.shape[1]}")

Number of columns: 15

C:\Users\soumy\AppData\Local\Temp\ipykernel_10364\943107714.py:4: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('a9a.txt', header=None, delim_whitespace=True)

In [2]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,-1,3:1,11:1,14:1,19:1,39:1,42:1,55:1,64:1,67:1,73:1,75:1,76:1,80:1,83:1
1,-1,5:1,7:1,14:1,19:1,39:1,40:1,51:1,63:1,67:1,73:1,74:1,76:1,78:1,83:1
2,-1,3:1,6:1,17:1,22:1,36:1,41:1,53:1,64:1,67:1,73:1,74:1,76:1,80:1,83:1
3,-1,5:1,6:1,17:1,21:1,35:1,40:1,53:1,63:1,71:1,73:1,74:1,76:1,80:1,83:1
4,-1,2:1,6:1,18:1,19:1,39:1,40:1,52:1,61:1,71:1,72:1,74:1,76:1,80:1,95:1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,-1,2:1,6:1,17:1,24:1,38:1,40:1,47:1,61:1,67:1,72:1,74:1,76:1,79:1,83:1
32557,1,3:1,6:1,15:1,22:1,36:1,40:1,54:1,63:1,67:1,73:1,74:1,76:1,80:1,83:1
32558,-1,5:1,6:1,15:1,22:1,36:1,44:1,55:1,66:1,67:1,72:1,74:1,76:1,80:1,83:1
32559,-1,1:1,6:1,17:1,22:1,36:1,42:1,55:1,62:1,67:1,73:1,74:1,76:1,78:1,83:1
32560,1,5:1,8:1,18:1,22:1,36:1,40:1,51:1,61:1,67:1,72:1,75:1,76:1,80:1,83:1