In [18]:
#Going with option 2, because in my spark, both of the solutions were not working
#I think MLLib is being phased out.

In [19]:
import pandas as pd

In [20]:
df = pd.read_csv("users_no_labels.txt", header=None)

In [21]:
x = df.corr(method='pearson')

In [22]:
x

          0             1             2
0  1.000000 -7.071068e-01 -3.333333e-01
1 -0.707107  1.000000e+00  3.925231e-17
2 -0.333333  3.925231e-17  1.000000e+00

In [23]:
#part = 3, colon cancer dataset. 

colon_cancer = pd.read_csv("colon_cancer_no_labels.txt", sep=" ",header=None) #separator is white space

In [24]:
colon_cancer

,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000
0,2.080750,1.099070,0.927763,1.029080,-0.130763,1.265460,-0.436286,0.728881,2.107980,1.359870,...,-0.138451,0.382957,0.876697,-0.216234,-1.408300,0.393327,-0.148522,1.591530,-0.217481,NaN
1,1.109460,0.786453,0.445560,-0.146323,-0.996316,0.555759,0.290734,-0.145259,1.132660,0.559093,...,-0.205499,-1.815370,0.324373,-1.296910,-0.870757,1.108740,1.094010,-0.492141,-1.554080,NaN
2,-0.676530,1.693100,1.559250,1.559980,-0.982179,-1.358510,-1.313990,-0.455067,0.295214,0.290694,...,1.230160,-2.039000,2.366090,0.820656,1.404500,0.176860,-0.086285,-0.390878,-0.089465,NaN
3,0.534396,1.677540,1.489030,0.778605,-0.183776,-1.116850,-1.487560,-0.579511,0.292683,1.345480,...,-0.593149,-4.440580,1.720710,-0.124617,-0.435880,0.228440,-0.893938,1.005880,-0.631247,NaN
4,-1.018900,0.511080,0.755641,1.013820,0.529899,0.160440,-0.087055,1.295290,0.458736,0.714082,...,0.497628,-0.083921,-0.382733,-0.913389,1.122930,0.834571,-0.283786,-2.860340,0.280871,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,0.488711,0.764970,0.920233,-0.958693,-0.147683,0.588944,0.097142,-0.212724,-0.827331,1.041480,...,-2.880040,0.322515,1.150150,1.132340,0.437734,0.174756,0.511431,-0.685264,-0.604012,NaN
58,-0.146703,0.112155,0.282926,-1.135510,0.683854,1.449190,0.963985,0.394901,-0.543475,0.382079,...,-1.315630,0.404797,-0.364126,-1.347500,0.075607,-2.387870,0.347011,-1.013400,-0.013589,NaN
59,0.200706,-0.668545,-0.935933,-0.886086,-1.372160,0.128890,0.488561,-2.447960,-0.445897,-0.317157,...,0.514963,-1.398880,0.771972,0.203989,-0.214999,0.585247,0.605018,1.344910,-2.485070,NaN
60,0.829749,0.299447,0.130738,0.335530,-0.401385,0.495544,-0.646200,-1.041640,-0.267708,-0.710770,...,0.436470,0.082887,-0.121180,0.407349,0.664057,0.533698,0.985630,-0.210661,-0.391249,NaN
61,0.566684,-0.533660,-0.761951,-0.087032,-0.283129,0.832089,-0.330326,-0.583525,-0.258754,-0.811779,...,-0.540061,0.915846,1.025730,0.786296,0.870661,0.154527,-0.453840,0.194535,0.064150,NaN

In [25]:
colon_correlation = colon_cancer.corr(method="pearson")

In [26]:
colon_correlation

,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000
0,1.000000,0.195989,0.183012,0.364940,0.078270,0.299429,0.257271,0.013403,0.670331,0.127926,...,0.029334,-0.132262,-0.116718,0.099190,-0.294966,0.404843,0.395296,0.125701,-0.139342,NaN
1,0.195989,1.000000,0.975337,0.257579,0.016923,0.242866,-0.031637,0.199475,0.311937,0.758122,...,-0.040670,-0.328019,0.472197,-0.201454,-0.227529,-0.315383,-0.304980,-0.150872,-0.311118,NaN
2,0.183012,0.975337,1.000000,0.199202,0.061213,0.269894,-0.019538,0.248290,0.306878,0.768006,...,-0.068198,-0.263027,0.448220,-0.208048,-0.232331,-0.348393,-0.329452,-0.198227,-0.263394,NaN
3,0.364940,0.257579,0.199202,1.000000,-0.002299,-0.088817,-0.072195,0.182836,0.583374,0.112045,...,0.212992,-0.382727,-0.097434,0.159654,-0.063352,0.113378,0.053409,-0.004881,-0.056931,NaN
4,0.078270,0.016923,0.061213,-0.002299,1.000000,0.026095,0.105075,0.647376,0.108042,0.032022,...,-0.102442,0.429310,-0.452167,-0.471924,-0.043853,-0.262944,-0.374552,-0.206077,0.658404,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,0.404843,-0.315383,-0.348393,0.113378,-0.262944,-0.027661,0.131455,-0.251618,0.337061,-0.288857,...,0.127651,-0.154913,-0.195298,0.326148,-0.043151,1.000000,0.593967,0.242056,-0.072454,NaN
1997,0.395296,-0.304980,-0.329452,0.053409,-0.374552,-0.076079,0.051168,-0.466106,0.253628,-0.282934,...,-0.008187,0.037329,0.041458,0.462065,0.195640,0.593967,1.000000,0.153457,-0.253962,NaN
1998,0.125701,-0.150872,-0.198227,-0.004881,-0.206077,0.029839,-0.118475,-0.193888,0.075410,-0.128839,...,-0.228482,-0.157360,0.067915,0.268218,-0.128509,0.242056,0.153457,1.000000,-0.011580,NaN
1999,-0.139342,-0.311118,-0.263394,-0.056931,0.658404,-0.021663,-0.011389,0.500996,-0.076157,-0.161503,...,-0.092490,0.445903,-0.476326,-0.318833,0.034779,-0.072454,-0.253962,-0.011580,1.000000,NaN
2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
colon_correlation = colon_cancer.corr(method="spearman")
colon_correlation

,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000
0,1.000000,0.248621,0.207575,0.303669,0.023595,0.322052,0.236534,-0.037949,0.648460,0.146886,...,0.015638,-0.107502,-0.073808,0.195034,-0.308101,0.397346,0.437385,0.122258,-0.262673,NaN
1,0.248621,1.000000,0.963385,0.308957,-0.024855,0.255572,-0.001184,0.182594,0.387072,0.737705,...,-0.032107,-0.247916,0.436428,-0.175946,-0.247060,-0.207172,-0.182191,-0.107250,-0.419707,NaN
2,0.207575,0.963385,1.000000,0.265795,0.059857,0.258190,0.008335,0.242981,0.350155,0.750900,...,-0.022538,-0.174183,0.417491,-0.203898,-0.227771,-0.293143,-0.258845,-0.190652,-0.375085,NaN
3,0.303669,0.308957,0.265795,1.000000,-0.012314,-0.066808,-0.059253,0.154340,0.607363,0.114301,...,0.192868,-0.390194,-0.127748,0.140238,-0.087809,0.073355,0.006875,0.034575,-0.066506,NaN
4,0.023595,-0.024855,0.059857,-0.012314,1.000000,0.006321,0.076075,0.627156,0.032057,0.056030,...,-0.168744,0.464884,-0.368790,-0.343960,-0.002292,-0.285689,-0.352824,-0.166276,0.553776,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,0.397346,-0.207172,-0.293143,0.073355,-0.285689,0.006774,0.110524,-0.279444,0.348694,-0.207726,...,0.116769,-0.135705,-0.190250,0.302460,-0.050490,1.000000,0.610889,0.268716,-0.090932,NaN
1997,0.437385,-0.182191,-0.258845,0.006875,-0.352824,-0.012163,0.086147,-0.471280,0.278437,-0.187580,...,0.009695,-0.009544,0.004205,0.453451,0.187278,0.610889,1.000000,0.131173,-0.202085,NaN
1998,0.122258,-0.107250,-0.190652,0.034575,-0.166276,0.019466,-0.174939,-0.122661,0.136965,-0.112186,...,-0.261867,-0.181184,0.056030,0.253305,-0.174435,0.268716,0.131173,1.000000,0.018005,NaN
1999,-0.262673,-0.419707,-0.375085,-0.066506,0.553776,-0.162147,-0.073053,0.450983,-0.137519,-0.250686,...,-0.134698,0.398454,-0.464431,-0.226058,0.146332,-0.090932,-0.202085,0.018005,1.000000,NaN
2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
number_pairwise = 2000*(2000-1)//2 #formula to calculate.
print(number_pairwise)

1999000